### ISSUE TITLE
郵便番号が間違っている時にt[0]がundefinedであるエラーがでる

### ISSUE THREAD

**Issue by shota** [yubinbango/yubinbango-core#2]
郵便番号が正しくない際にt[0]がundefinedであるというエラーが出ます。jsなので、try~catchが使いづらいことから、何かしらエラーを返すのが良いのではないかと思います。

**Comment by koba-ninkigumi** [comment]
とりあえず対処してみましたが、ご希望のエラーの形式などがあればご掲示ください。

**Comment by shota** [comment]
結構この手の実装がcallbackとerrorを渡せるようにしておく実装だったり、.done().error()実装だったりするので、そういう方が一般的かなーとか思っていました。

**Comment by koba-ninkigumi** [comment]
どちらが良いですかね？それではソースのTypeScriptファイルとテストの変更をPull Requestでお願いします。

**Comment by shota** [comment]
こちらとして考えられる実装やってみます。

**Comment by koba-ninkigumi** [comment]
よろしくお願いします。m(__)m

近く予定されているTypeScript 2.0のリリース後は（ブラウザでの検証結果次第では）TypeScriptのコードはasync/awaitで書き換えもありかなと思っています。

**Comment by shota** [comment]
[Pull request](https://github.com/yubinbango/yubinbango-core/pull/3)
こちらをご参照ください。

**Comment by koba-ninkigumi** [comment]
ありがとうございました。m(__)m
